server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kryption
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      validation-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql


management:
  endpoints:
    web:
      exposure:
        include: '*'
